### ISSUE TITLE
Exercise 1.5 takes meta-language statement on left side for granted?

### ISSUE THREAD

**Issue by mattmccutchen** [fintelkai/fintel-heim-intensional-notes#2]
Thanks for making these notes available!  I'm looking forward to studying them by myself.  You said you welcome comments and I have a minor comment which I don't know if you'll consider worth your time; I'm filing it as an issue so the discussion will be visible to anyone else interested, who can calibrate their feedback accordingly.

I was thrown by Exercise 1.5 and Section 1.4.  This exercise and section criticize the use of "Watson is slow in w" for its truth value on the right side of (33) while taking for granted the use of "x is slow in w" for its truth value inside the lambda.

I can conceive of two ways to repair the exposition:
1. Find an equivalent expression to use on the left side of (33) without using a meta-language statement for its truth value.  Still, a reader familiar with the H & K convention might object that the only thing "wrong" with (33) is that H & K chose, arguably arbitrarily, to restrict the convention to lambda bodies.
2. Give up on puzzling the reader, drop Exercise 1.5, and be upfront in Section 1.4 with a review of the H & K convention and a discussion of the option of extending it to any meta-language statement used where a truth value is expected.

**Comment by fintelkai** [comment]
Thank you for the comment. The notes presuppose that the reader has worked through H&K. Exercise 1.5 is meant to see whether a lesson that comes up a lot when teaching H&K has been learned. Section 1.4 then discusses the confusion that often arises. Puzzling the reader is used as a pedagogical device. This is one way in which the notes are not quite standalone but meant to accompany a live teaching environment. 

In 1.4, we do discuss the option of expanding the H&K convention (which is what von Stechow does). We decided not to go that way, partially for consistency with H&K.

I don't understand the comment about finding "an equivalent expression to use on the left side of (33)". There's nothing wrong with the left side of (33). It's a perfectly good expression denoting a truth-value.

**Comment by mattmccutchen** [comment]
Thanks for the response!  I agree that puzzling the reader is a useful technique if it can be done in a way that makes sense.

Let me try to explain more carefully what I find infelicitous (to borrow a linguistics term!) about Section 1.4.  It says, "The function [on the left side of (33)] is a function from individuals to truth-values that will deliver the truth-value 1 iff the individual is slow in world w."  In order to accept this statement, the reader has to be comfortable with the use of a meta-language statement for its truth value, at least for the body of a lambda.  At this point, either (1) the reader is aware of a distinction between what is allowed for lambda bodies and in other contexts (as in H&K) or (2) the reader is not aware of such a distinction.  A reader of type (1) must be clear on the distinction between a meta-language sentence and its truth value, so reintroducing that distinction as if the reader might have forgotten it seems inappropriate.  On the other hand, to a reader of type (2), it will seem inconsistent that the text says that "Watson is slow in w" does not contribute a truth value while having taken for granted that "x is slow in w" does contribute a truth value.

I hope I've made the problem sufficiently clear, even though I expect I haven't argued it perfectly.  It's just a wrinkle in the exposition; the point is clear after reading the section.  Of course, it's your prerogative not to focus on ironing out this kind of thing for a document billed as "lecture notes" rather than a textbook.

**Comment by fintelkai** [comment]
Thanks for the elaboration. I agree that an ideal reader, which you seem to be, would not have forgotten H&K's convention and its limits. But, having taught this material to hundreds of students, I know that actual readers are not ideal. They do forget and do get confused, quite often in fact. An exercise early in the course that is meant to flush out such lapses of memories and confusions makes a lot of sense. And then one discusses the issues.

We probably will continue to work on this part of the text. In addition to lapses of memory and superficial confusion, there's also a larger confusion that is quite widespread: not distinguishing between (i) semantics as translating one language into another language and (ii) denotational semantics. In the end, this may be behind some of the mistakes students consistently make.
